name: Python 3.7 application test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.17
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.17
    - name: Install dependencies
      run: |
        make install-azure
    - name: Lint with Pylint
      run: |
        make lint
    - name: Test with Pytest
      run: |
        make test
